name: finbert
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - pandas=0.23.4
  - python=3.7.3
  - numpy==1.16.3
  - nltk
  - tqdm
  - ipykernel=5.1.3
  - textblob
  - pip:
    - joblib==0.13.2
    - pytorch-pretrained-bert==0.6.2
    - scikit-learn==0.21.2
    - spacy==2.1.4
    - torch==1.1.0